/**
 * eat — server bootstrap.
 *
 * Imports the assembled router (app/router.ts) and serves it over a Node http
 * server. The router import also runs the DB migrations at module load (app/db.ts).
 *
 * The createRequestListener wrapper passes ONLY the request to router.fetch (the
 * listener's 2nd arg would otherwise be mistaken for RequestInit).
 *
 * NOTE FOR FEATURE AGENTS: do not edit this file. All /week*, /ideas*, /grocery*,
 * /settings* routing is delegated into the matching app/routes/*.tsx module via
 * its registerRoutes(router) call inside app/router.ts. Add routes there.
 */
import * as http from "node:http";
import { createRequestListener } from "remix/node-fetch-server";

import { router } from "./app/router.ts";
import { PORT } from "./app/config.ts";

const server = http.createServer(createRequestListener((request) => router.fetch(request)));
server.listen(PORT, () => {
  console.log(`eat running at http://localhost:${PORT}`);
});
